import { createHash } from "node:crypto";
import { prisma } from "../db/prisma.js";
import { badRequest } from "../errors/httpError.js";
import { createLifeActionPlan, nextLifeActionState, persistLifeActionPlan, serializeLifeTransaction, transitionPersistedLifeTransaction, validateLifeActionPlan } from "./lifeTransactionService.js";

export type SandboxRestaurantSlot = { id: string; restaurantId: string; restaurantName: string; cuisine: string; location: string; dateTime: string; partySize: number; mode: "sandbox" };
export type SandboxEvent = { id: string; name: string; location: string; startsAt: string; category: string; priceFrom: string; currency: string; purchaseUrl: null; mode: "sandbox" };
const req = (value: unknown, label: string) => { const text = String(value ?? "").trim(); if (!text) throw badRequest(`${label} is required.`); return text; };

export function searchSandboxRestaurants(input: { location?: unknown; cuisine?: unknown; dateTime?: unknown; partySize?: unknown }) { const location = req(input.location, "Location"); const cuisine = req(input.cuisine, "Cuisine"); const dateTime = new Date(req(input.dateTime, "Date and time")); const partySize = Number(input.partySize); if (Number.isNaN(dateTime.valueOf())) throw badRequest("Date and time is invalid."); if (!Number.isInteger(partySize) || partySize < 1 || partySize > 20) throw badRequest("Party size must be between 1 and 20."); const seed = createHash("sha256").update(`${location}|${cuisine}|${dateTime.toISOString()}`).digest("hex").slice(0, 8); return ["Sandbox Table", "Example Bistro"].map((name, i) => ({ id: `restaurant-sandbox-${seed}-${i}`, restaurantId: `restaurant-${seed}-${i}`, restaurantName: name, cuisine, location, dateTime: new Date(dateTime.valueOf() + i * 30 * 60_000).toISOString(), partySize, mode: "sandbox" as const })); }
function slot(value: unknown): SandboxRestaurantSlot { if (!value || typeof value !== "object") throw badRequest("A complete sandbox restaurant slot is required."); const item = value as Partial<SandboxRestaurantSlot>; if (!String(item.id ?? "").startsWith("restaurant-sandbox-") || item.mode !== "sandbox") throw badRequest("Only sandbox restaurant slots can be reserved here."); return { id: String(item.id), restaurantId: req(item.restaurantId, "Restaurant"), restaurantName: req(item.restaurantName, "Restaurant name"), cuisine: req(item.cuisine, "Cuisine"), location: req(item.location, "Location"), dateTime: new Date(req(item.dateTime, "Date and time")).toISOString(), partySize: Number(item.partySize), mode: "sandbox" }; }
export async function reserveSandboxRestaurant(input: { userId: string; slot: unknown; confirmed: unknown; idempotencyKey: unknown }) { if (input.confirmed !== true) throw badRequest("Explicit reservation confirmation is required."); const selected = slot(input.slot); const key = req(input.idempotencyKey, "Idempotency key"); const values = { slot: selected, restaurantId: selected.restaurantId, dateTime: selected.dateTime, partySize: selected.partySize, approvalRequestId: `sandbox-approval:${key}` }; let plan = validateLifeActionPlan(createLifeActionPlan({ capabilityKey: "leisure.restaurant.reserve", executionLevel: "transact", providerId: "life-sandbox", idempotencyKey: key, values })); plan = nextLifeActionState(plan); const saved = await persistLifeActionPlan(input.userId, plan); if (saved.state === "confirmed") return serializeLifeTransaction(saved); if (saved.state !== "awaiting_approval") throw badRequest("This reservation is already being processed."); await transitionPersistedLifeTransaction({ userId: input.userId, id: saved.id, next: "executing" }); const reference = `TABLE-${createHash("sha256").update(key).digest("hex").slice(0, 8).toUpperCase()}`; return transitionPersistedLifeTransaction({ userId: input.userId, id: saved.id, next: "confirmed", externalReference: reference, result: { sandbox: true, status: "confirmed", reservationReference: reference, slot: selected } }); }
export async function cancelSandboxRestaurant(input: { userId: string; id: string; confirmed: unknown }) { if (input.confirmed !== true) throw badRequest("Explicit reservation cancellation confirmation is required."); const reservation = await prisma.lifeTransaction.findFirst({ where: { id: input.id, userId: input.userId, capabilityKey: "leisure.restaurant.reserve", providerId: "life-sandbox", state: "confirmed" } }); if (!reservation) throw badRequest("A confirmed sandbox reservation was not found."); return transitionPersistedLifeTransaction({ userId: input.userId, id: reservation.id, next: "cancelled", result: { sandbox: true, status: "cancelled", reservationReference: reservation.externalReference } }); }
export function searchSandboxEvents(input: { location?: unknown; startDate?: unknown; endDate?: unknown }) { const location = req(input.location, "Location"); const start = new Date(`${req(input.startDate, "Start date")}T18:00:00Z`); const end = new Date(`${req(input.endDate, "End date")}T23:59:59Z`); if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end < start) throw badRequest("Event date range is invalid."); const seed = createHash("sha256").update(`${location}|${start.toISOString()}`).digest("hex").slice(0, 8); return [{ id: `event-sandbox-${seed}-1`, name: "Sandbox Live Music Evening", location, startsAt: start.toISOString(), category: "music", priceFrom: "25.00", currency: "EUR", purchaseUrl: null, mode: "sandbox" }, { id: `event-sandbox-${seed}-2`, name: "Example Local Exhibition", location, startsAt: new Date(Math.min(end.valueOf(), start.valueOf() + 86400000)).toISOString(), category: "arts", priceFrom: "12.00", currency: "EUR", purchaseUrl: null, mode: "sandbox" }] satisfies SandboxEvent[]; }
