import { createHash } from "node:crypto";
import { env } from "../config/env.js";
import { prisma } from "../db/prisma.js";
import { httpError } from "../errors/httpError.js";
import { verifyConnectorState } from "./cryptoService.js";
import { getGooglePlaceDestination, searchGooglePlacesProviders } from "./googlePlacesHouseholdProvider.js";
import { createHitlRequest } from "./hitlService.js";
import { decodeJson, encodeJson } from "./jsonService.js";
import { serializeLifeTransaction } from "./lifeTransactionService.js";
import { getTicketmasterEventDestination, searchTicketmasterEvents } from "./ticketmasterProvider.js";

type Kind = "event" | "restaurant";
function requireLive() { if (env.LIVE_LEISURE_ENABLED !== "true") throw httpError(503, "Live leisure is not enabled for this environment.", "live_leisure_disabled"); }
function requireHandoff() { if (env.LIVE_LEISURE_ENABLED !== "true" || env.HOSTED_LEISURE_HANDOFF_ENABLED !== "true") throw httpError(503, "Hosted leisure handoff is not enabled for this environment.", "hosted_leisure_disabled"); }
function clean(value: unknown, label: string, max: number) { const text = String(value ?? "").trim(); if (!text || text.length > max) throw httpError(400, `${label} is invalid.`, "invalid_leisure_request"); return text; }
const hash = (value: Record<string, string>) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
export async function searchLiveRestaurants(input: { cuisine: string; location: string }) { requireLive(); if (!env.GOOGLE_PLACES_API_KEY) throw httpError(503, "Google Places is not configured.", "google_places_not_configured"); return searchGooglePlacesProviders({ query: `${input.cuisine} restaurants in ${input.location}`, timeoutMs: env.LEISURE_PROVIDER_TIMEOUT_MS }); }
export { searchTicketmasterEvents };

export async function prepareLeisureHandoff(input: { userId: string; agentId: string; kind: Kind; externalId: string; context: string; idempotencyKey: string }) { requireHandoff(); const request = { kind: input.kind, externalId: clean(input.externalId, "External ID", 300), context: clean(input.context, "Selection context", 500) }; const requestHash = hash(request); const existing = await prisma.lifeTransaction.findUnique({ where: { userId_idempotencyKey: { userId: input.userId, idempotencyKey: input.idempotencyKey } } }); if (existing) { const stored = decodeJson<Record<string, unknown>>(existing.inputJson, {}); if (stored.requestHash !== requestHash) throw httpError(409, "This idempotency key is bound to another leisure selection.", "leisure_idempotency_conflict"); return { transaction: serializeLifeTransaction(existing), replayed: true }; } const providerId = input.kind === "event" ? "ticketmaster" : "google-places"; const payload = { action: "open_leisure_provider_page", providerId, ...request, requestHash, purchaseOrReservationOccursExternally: true }; const approval = await createHitlRequest({ userId: input.userId, agentId: input.agentId, actionName: "leisure.hosted_handoff", payload, ttlMinutes: 10 }); const transaction = await prisma.lifeTransaction.create({ data: { userId: input.userId, capabilityKey: input.kind === "event" ? "leisure.event.search" : "leisure.restaurant.reserve", executionLevel: "redirect", state: "awaiting_approval", providerId, providerCandidatesJson: encodeJson([providerId]), approvalRequired: true, idempotencyKey: input.idempotencyKey, inputJson: encodeJson({ ...request, requestHash, approvalRequestId: approval.id }), hitlRequestId: approval.id } }); return { transaction: serializeLifeTransaction(transaction), approvalRequestId: approval.id, replayed: false, disclosure: "No ticket purchase or restaurant reservation has been made." }; }

export async function continueLeisureHandoff(input: { userId: string; transactionId: string }) { requireHandoff(); const transaction = await prisma.lifeTransaction.findFirst({ where: { id: input.transactionId, userId: input.userId } }); if (!transaction?.hitlRequestId) throw httpError(404, "A prepared leisure handoff was not found.", "leisure_handoff_not_found"); if (transaction.state === "executing") return { transaction: serializeLifeTransaction(transaction), destinationUrl: null, replayed: true }; if (transaction.state !== "awaiting_approval") throw httpError(409, "This leisure handoff is not waiting for approval.", "leisure_handoff_not_pending"); const approval = await prisma.hitlRequest.findFirst({ where: { id: transaction.hitlRequestId, userId: input.userId, status: "success", expiresAt: { gt: new Date() } } }); if (!approval) throw httpError(409, "Approve this exact leisure handoff before continuing.", "leisure_handoff_approval_required"); const signed = decodeJson<Record<string, unknown>>(approval.payload, {}); const verified = verifyConnectorState<Record<string, unknown>>(typeof signed.approvalBinding === "string" ? signed.approvalBinding : ""); const unsigned = Object.fromEntries(Object.entries(signed).filter(([key]) => key !== "approvalBinding")); if (!verified || JSON.stringify(verified) !== JSON.stringify(unsigned)) throw httpError(409, "The leisure approval payload changed.", "leisure_handoff_approval_invalid"); const stored = decodeJson<Record<string, unknown>>(transaction.inputJson, {}); const request = { kind: String(stored.kind ?? ""), externalId: String(stored.externalId ?? ""), context: String(stored.context ?? "") }; if (stored.requestHash !== hash(request) || unsigned.requestHash !== stored.requestHash) throw httpError(409, "The approved leisure selection changed.", "leisure_selection_changed"); const destinationUrl = request.kind === "event" ? (await getTicketmasterEventDestination(request.externalId)).url : await getGooglePlaceDestination(request.externalId, env.LEISURE_PROVIDER_TIMEOUT_MS); const claimed = await prisma.lifeTransaction.updateMany({ where: { id: transaction.id, userId: input.userId, state: "awaiting_approval" }, data: { state: "executing", resultJson: encodeJson({ status: "redirected_to_leisure_provider", providerId: transaction.providerId, destinationHost: new URL(destinationUrl).hostname, returnIsConfirmation: false, purchaseOrReservationStatusAvailable: false }) } }); if (!claimed.count) { const current = await prisma.lifeTransaction.findFirstOrThrow({ where: { id: transaction.id, userId: input.userId } }); return { transaction: serializeLifeTransaction(current), destinationUrl: null, replayed: true }; } const current = await prisma.lifeTransaction.findFirstOrThrow({ where: { id: transaction.id, userId: input.userId } }); return { transaction: serializeLifeTransaction(current), destinationUrl, replayed: false, disclosure: "Opening this provider page does not confirm a purchase or reservation." }; }
