import { createHash } from "node:crypto";
import { prisma } from "../db/prisma.js";
import { badRequest } from "../errors/httpError.js";
import { decodeJson } from "./jsonService.js";
import { createLifeActionPlan, nextLifeActionState, persistLifeActionPlan, serializeLifeTransaction, transitionPersistedLifeTransaction, validateLifeActionPlan } from "./lifeTransactionService.js";

export type SandboxHomeDevice = { entityId: string; name: string; room: string; kind: "light" | "thermostat" | "plug"; state: string; allowedCommands: string[]; mode: "sandbox" };
const defaults: SandboxHomeDevice[] = [
  { entityId: "light.living_room", name: "Living room light", room: "Living room", kind: "light", state: "off", allowedCommands: ["turn_on", "turn_off"], mode: "sandbox" },
  { entityId: "climate.hallway", name: "Hallway thermostat", room: "Hallway", kind: "thermostat", state: "20", allowedCommands: ["set_18", "set_19", "set_20", "set_21", "set_22"], mode: "sandbox" },
  { entityId: "switch.desk", name: "Desk plug", room: "Office", kind: "plug", state: "on", allowedCommands: ["turn_on", "turn_off"], mode: "sandbox" }
];
export async function listSandboxHomeDevices(userId: string) { const latest = await prisma.lifeTransaction.findMany({ where: { userId, capabilityKey: "home.device.control", providerId: "life-sandbox", state: "confirmed" }, orderBy: { createdAt: "desc" }, take: 100 }); const states = new Map<string, string>(); for (const row of latest) { const result = decodeJson<{ entityId?: string; state?: string }>(row.resultJson, {}); if (result.entityId && result.state && !states.has(result.entityId)) states.set(result.entityId, result.state); } return defaults.map((device) => ({ ...device, state: states.get(device.entityId) ?? device.state })); }
export async function controlSandboxHomeDevice(input: { userId: string; entityId: unknown; command: unknown; confirmed: unknown; idempotencyKey: unknown }) { if (input.confirmed !== true) throw badRequest("Explicit device-control confirmation is required."); const entityId = String(input.entityId ?? ""); const command = String(input.command ?? ""); const key = String(input.idempotencyKey ?? "").trim(); const device = defaults.find((item) => item.entityId === entityId); if (!device) throw badRequest("Device is not in the sandbox allowlist."); if (!device.allowedCommands.includes(command)) throw badRequest("Command is not allowed for this device."); if (!key) throw badRequest("Idempotency key is required."); const values = { connectionId: "smart-home-sandbox", entityId, command, approvalRequestId: `sandbox-approval:${key}` }; let plan = validateLifeActionPlan(createLifeActionPlan({ capabilityKey: "home.device.control", executionLevel: "transact", providerId: "life-sandbox", idempotencyKey: key, values })); plan = nextLifeActionState(plan); const saved = await persistLifeActionPlan(input.userId, plan); if (saved.state === "confirmed") return serializeLifeTransaction(saved); if (saved.state !== "awaiting_approval") throw badRequest("This device command is already being processed."); await transitionPersistedLifeTransaction({ userId: input.userId, id: saved.id, next: "executing" }); const state = command === "turn_on" ? "on" : command === "turn_off" ? "off" : command.replace("set_", ""); const reference = `HOME-${createHash("sha256").update(key).digest("hex").slice(0, 8).toUpperCase()}`; return transitionPersistedLifeTransaction({ userId: input.userId, id: saved.id, next: "confirmed", externalReference: reference, result: { sandbox: true, entityId, command, state, status: "confirmed" } }); }
export function analyzeSandboxEnergy(input: { startDate?: unknown; endDate?: unknown }) { const startDate = String(input.startDate ?? ""); const endDate = String(input.endDate ?? ""); const start = new Date(`${startDate}T00:00:00Z`); const end = new Date(`${endDate}T23:59:59Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(endDate) || end < start) throw badRequest("Energy date range is invalid."); const days = Math.max(1, Math.ceil((end.valueOf() - start.valueOf()) / 86400000)); return { sandbox: true, readOnly: true, startDate, endDate, currency: "EUR", totalKwh: Number((days * 8.4).toFixed(1)), estimatedCost: Number((days * 8.4 * 0.34).toFixed(2)), carbonKg: Number((days * 8.4 * 0.38).toFixed(1)), peakHour: "19:00–20:00", recommendations: ["Shift dishwasher use outside the evening peak.", "Turn off the desk plug overnight."], source: "deterministic sandbox data" }; }
