import { env } from "../config/env.js";
import { httpError } from "../errors/httpError.js";
import { validateExternalUrl } from "./policy/externalUrlPolicyService.js";

type RawEvent = Record<string, any>;
export type LiveEvent = { providerId: "ticketmaster"; eventId: string; name: string; startsAt: string; venue: string; location: string; category: string; salesStatus: string; price: { min: string; max: string; currency: string } | null; officialUrlAvailable: boolean; retrievedAt: string; mode: "live" };
function requireLive() { if (env.LIVE_LEISURE_ENABLED !== "true") throw httpError(503, "Live leisure is not enabled for this environment.", "live_leisure_disabled"); if (!env.TICKETMASTER_API_KEY) throw httpError(503, "Ticketmaster is not configured.", "ticketmaster_not_configured"); }
async function request(path: string, params: URLSearchParams) { requireLive(); params.set("apikey", env.TICKETMASTER_API_KEY!); const controller = new globalThis.AbortController(); const timer = setTimeout(() => controller.abort(), env.LEISURE_PROVIDER_TIMEOUT_MS); try { const response = await fetch(`https://app.ticketmaster.com/discovery/v2/${path}?${params}`, { signal: controller.signal, headers: { Accept: "application/json" } }); if (!response.ok) throw httpError(response.status === 429 ? 503 : 502, "Ticketmaster could not complete the request.", response.status === 429 ? "ticketmaster_rate_limited" : "ticketmaster_provider_error"); return await response.json() as RawEvent; } catch (error) { if (error instanceof Error && error.name === "AbortError") throw httpError(504, "Ticketmaster timed out.", "ticketmaster_timeout"); throw error; } finally { clearTimeout(timer); } }
export function normalizeTicketmasterEvent(raw: RawEvent, now = new Date()): LiveEvent | null { const id = typeof raw.id === "string" ? raw.id : ""; const name = typeof raw.name === "string" ? raw.name.trim() : ""; const startsAt = raw.dates?.start?.dateTime; if (!id || !name || typeof startsAt !== "string" || Number.isNaN(Date.parse(startsAt)) || raw.test === true) return null; const venue = raw._embedded?.venues?.[0]; const range = raw.priceRanges?.find((item: any) => typeof item?.min === "number" && typeof item?.max === "number" && typeof item?.currency === "string"); return { providerId: "ticketmaster", eventId: id, name, startsAt: new Date(startsAt).toISOString(), venue: typeof venue?.name === "string" ? venue.name : "Venue to be confirmed", location: [venue?.city?.name, venue?.country?.countryCode].filter(Boolean).join(", "), category: raw.classifications?.[0]?.segment?.name ?? "Other", salesStatus: raw.dates?.status?.code ?? "unknown", price: range ? { min: range.min.toFixed(2), max: range.max.toFixed(2), currency: range.currency.toUpperCase() } : null, officialUrlAvailable: typeof raw.url === "string", retrievedAt: now.toISOString(), mode: "live" }; }
export async function searchTicketmasterEvents(input: { city: string; startDate: string; endDate: string; keyword?: string }) { const start = new Date(`${input.startDate}T00:00:00Z`); const end = new Date(`${input.endDate}T23:59:59Z`); if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end < start || end.valueOf() - start.valueOf() > 31 * 86400000) throw httpError(400, "Event dates must be a valid range of at most 31 days.", "invalid_event_range"); const params = new URLSearchParams({ city: input.city, startDateTime: start.toISOString().replace(".000", ""), endDateTime: end.toISOString().replace(".000", ""), includeTBA: "no", includeTBD: "no", includeTest: "no", size: "20", sort: "date,asc" }); if (input.keyword) params.set("keyword", input.keyword); const body = await request("events.json", params); const now = new Date(); const events = (Array.isArray(body._embedded?.events) ? body._embedded.events : []).map((item: RawEvent) => normalizeTicketmasterEvent(item, now)).filter((item: LiveEvent | null): item is LiveEvent => Boolean(item)); return { events, attribution: { source: "Ticketmaster Discovery API", purchaseOccursExternally: true } }; }
export async function getTicketmasterEventDestination(eventId: string) { if (!/^[A-Za-z0-9_-]{5,100}$/.test(eventId)) throw httpError(400, "A valid Ticketmaster event ID is required.", "invalid_event_id"); const raw = await request(`events/${encodeURIComponent(eventId)}.json`, new URLSearchParams()); const event = normalizeTicketmasterEvent(raw); if (!event || event.eventId !== eventId || event.salesStatus !== "onsale" || typeof raw.url !== "string") throw httpError(409, "This event is no longer eligible for ticket handoff.", "event_handoff_stale"); const decision = validateExternalUrl(raw.url); if (!decision.allowed) throw httpError(502, "The official event URL did not pass safety checks.", "unsafe_event_destination"); return { url: decision.url.toString(), event }; }
