import { useCallback, useEffect, useState, type FormEvent } from "react";
import { BarChart3, Clipboard, RotateCcw, UserPlus, XCircle } from "lucide-react";
import { createBetaInvite, getBetaMetrics, listBetaFeedback, listBetaInvites, replaceBetaInvite, revokeBetaInvite, updateBetaFeedback, type BetaFeedback, type BetaInvite, type BetaMetrics } from "../api/beta";

export function BetaAdminPanel({ className = "" }: { className?: string }) {
  const [invites, setInvites] = useState<BetaInvite[]>([]); const [feedback, setFeedback] = useState<BetaFeedback[]>([]); const [metrics, setMetrics] = useState<BetaMetrics | null>(null);
  const [email, setEmail] = useState(""); const [cohort, setCohort] = useState("trusted"); const [filterCohort, setFilterCohort] = useState(""); const [feedbackStatus, setFeedbackStatus] = useState("");
  const [token, setToken] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const refresh = useCallback(async () => { setError(""); try { const [a,b,c] = await Promise.all([listBetaInvites(), listBetaFeedback(feedbackStatus), getBetaMetrics(filterCohort)]); setInvites(a.invites); setFeedback(b.feedback); setMetrics(c.metrics); } catch (caught) { setError(caught instanceof Error ? caught.message : "Beta administration could not be loaded."); } }, [feedbackStatus, filterCohort]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function create(event: FormEvent) { event.preventDefault(); setBusy("create"); setError(""); try { const result = await createBetaInvite({ email, cohort, ttlDays: 7 }); setToken(result.token); setEmail(""); setNotice("Invite created. Copy the token now; it will not be shown again."); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Invite could not be created."); } finally { setBusy(""); } }
  async function inviteAction(invite: BetaInvite, action: "revoke" | "replace") { setBusy(invite.id); setToken(""); try { if (action === "revoke") await revokeBetaInvite(invite.id); else { const result = await replaceBetaInvite(invite.id); setToken(result.token); setNotice("Replacement created. Copy its token now."); } await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Invite could not be updated."); } finally { setBusy(""); } }
  async function triage(item: BetaFeedback, status: "triaged" | "resolved") { setBusy(item.id); try { await updateBetaFeedback(item.id, status); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Feedback could not be updated."); } finally { setBusy(""); } }
  return <section className={`panel beta-admin ${className}`} id="beta"><div className="creator-panel-header"><div><div className="panel-title">Private beta</div><h2>Invites, support, and safe rollout</h2><p>Grow cohorts deliberately and pause expansion when safety or support signals degrade.</p></div><span className="status-pill blue">{metrics?.cohort ?? "all"}</span></div>
    {error ? <div className="friendly-error" role="alert">{error}<button onClick={() => void refresh()} type="button">Retry</button></div> : null}
    <div className="beta-metrics">{[["Invites",metrics?.invites ?? 0],["Redeemed",metrics?.redeemed ?? 0],["Activation",`${Math.round((metrics?.activationRate ?? 0)*100)}%`],["Installs",metrics?.installs ?? 0],["Successful runs",metrics?.successfulRuns ?? 0],["Support contacts",metrics?.supportContacts ?? 0]].map(([label,value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
    <div className="beta-admin-grid"><section className="beta-admin-card"><div className="beta-card-heading"><h3><UserPlus aria-hidden="true" size={18}/> Invite people</h3><select aria-label="Metrics cohort" autoComplete="off" name="metrics-cohort" value={filterCohort} onChange={(e) => setFilterCohort(e.target.value)}><option value="">All metrics</option>{["team","trusted","early","expanded"].map((item)=><option key={item}>{item}</option>)}</select></div>
      <form className="beta-invite-form" onSubmit={(event) => void create(event)}><input aria-label="Invite email" autoComplete="email" name="invite-email" placeholder="person@example.com" required spellCheck={false} type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/><select aria-label="Invite cohort" autoComplete="off" name="invite-cohort" value={cohort} onChange={(e)=>setCohort(e.target.value)}>{["team","trusted","early","expanded"].map((item)=><option key={item}>{item}</option>)}</select><button disabled={busy==="create"} type="submit">Create invite</button></form>
      {token ? <div className="beta-token"><strong>One-time invite token</strong><code>{token}</code><button onClick={() => void navigator.clipboard.writeText(token)} type="button"><Clipboard size={15}/> Copy token</button></div> : null}{notice ? <p role="status">{notice}</p> : null}
      <div className="beta-list">{invites.slice(0,20).map((invite)=><article key={invite.id}><div><strong>{invite.email}</strong><span>{invite.cohort} · {invite.status} · expires {new Date(invite.expiresAt).toLocaleDateString()}</span></div>{invite.status==="pending"?<div><button disabled={busy===invite.id} onClick={()=>void inviteAction(invite,"replace")} type="button"><RotateCcw size={14}/> Replace</button><button disabled={busy===invite.id} onClick={()=>void inviteAction(invite,"revoke")} type="button"><XCircle size={14}/> Revoke</button></div>:null}</article>)}</div>
    </section><section className="beta-admin-card"><div className="beta-card-heading"><h3><BarChart3 aria-hidden="true" size={18}/> Feedback triage</h3><select aria-label="Feedback status" autoComplete="off" name="feedback-status" value={feedbackStatus} onChange={(e)=>setFeedbackStatus(e.target.value)}><option value="">All</option>{["open","triaged","resolved"].map((item)=><option key={item}>{item}</option>)}</select></div>
      <div className="beta-list">{feedback.length?feedback.map((item)=><article key={item.id}><div><strong>{item.category.replace(/_/g," ")} · {item.severity}</strong><span>{item.expectedResult}</span><small>{item.actualResult}</small></div><div>{item.status==="open"?<button disabled={busy===item.id} onClick={()=>void triage(item,"triaged")} type="button">Triage</button>:null}{item.status!=="resolved"?<button disabled={busy===item.id} onClick={()=>void triage(item,"resolved")} type="button">Resolve</button>:<span className="status-pill green">resolved</span>}</div></article>):<p className="empty">No feedback matches this filter.</p>}</div>
    </section></div>
  </section>;
}
