import { createHash, randomUUID } from "node:crypto";
import { env } from "../../config/env.js";
import { prisma } from "../../db/prisma.js";
import { decodeJson, encodeJson } from "../jsonService.js";
import type { ProviderAdapter, ProviderExecutionInput, ProviderExecutionResult } from "./providerAdapterTypes.js";

type FetchLike = typeof fetch;
type Activity = Record<string, unknown>;
type ActivityResult = { values: Activity[] } | { error: ProviderExecutionResult };
let stravaFetch: FetchLike = fetch;
export function setStravaFetchForTest(value: FetchLike) { stravaFetch = value; }
export function resetStravaFetchForTest() { stravaFetch = fetch; }
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function blocked(input: ProviderExecutionInput, reason: string, code: "invalid_input" | "connector_not_connected" | "connector_expired" | "provider_error" = "invalid_input", retryable = false): ProviderExecutionResult { return { status: "blocked", toolRunId: input.previousToolRunId ?? randomUUID(), reason, code, userMessage: reason, retryable, nextAction: code === "connector_not_connected" || code === "connector_expired" ? "connect_account" : code === "provider_error" ? "try_again" : "add_missing_info" }; }
function range(input: ProviderExecutionInput, fallbackDays = 14) {
  const fallbackEnd = new Date(); const fallbackStart = new Date(fallbackEnd.valueOf() - fallbackDays * 86_400_000);
  const startText = text(input.input.startDate); const endText = text(input.input.endDate);
  const start = startText ? new Date(`${startText}T00:00:00Z`) : fallbackStart; const end = endText ? new Date(`${endText}T23:59:59Z`) : fallbackEnd;
  if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end < start || end.valueOf() - start.valueOf() > 31 * 86_400_000 || end > new Date(Date.now() + 86_400_000)) return null;
  return { start, end, startDate: start.toISOString().slice(0, 10), endDate: end.toISOString().slice(0, 10) };
}
function credentials(input: ProviderExecutionInput) { const token = text(input.providerConnection?.credentials.accessToken); const scopes = text(input.providerConnection?.credentials.grantedScopes).split(/[\s,]+/).filter(Boolean); if (!token || !scopes.includes("activity:read")) return null; return token; }
async function activities(input: ProviderExecutionInput, dates: NonNullable<ReturnType<typeof range>>): Promise<ActivityResult> {
  if (env.LIVE_WELLNESS_ENABLED !== "true") return { error: blocked(input, "Live wellness access is not enabled in this environment.") };
  const token = credentials(input); if (!token) return { error: blocked(input, "Reconnect Strava and grant the activity:read scope before reading activity data.", "connector_not_connected") };
  try {
    const url = new URL("https://www.strava.com/api/v3/athlete/activities"); url.searchParams.set("after", String(Math.floor(dates.start.valueOf() / 1000))); url.searchParams.set("before", String(Math.floor(dates.end.valueOf() / 1000))); url.searchParams.set("page", "1"); url.searchParams.set("per_page", "200");
    const response = await stravaFetch(url, { method: "GET", signal: globalThis.AbortSignal.timeout(env.WELLNESS_PROVIDER_TIMEOUT_MS), headers: { Accept: "application/json", Authorization: `Bearer ${token}` } });
    if (!response.ok) return { error: blocked(input, response.status === 401 ? "Reconnect Strava; its consent or token is no longer valid." : `Strava returned HTTP ${response.status}.`, response.status === 401 ? "connector_expired" : "provider_error", response.status === 429 || response.status >= 500) };
    const body = await response.json(); if (!Array.isArray(body)) return { error: blocked(input, "Strava returned an invalid activity response.", "provider_error") };
    return { values: body as Activity[] };
  } catch { return { error: blocked(input, "Strava could not be reached.", "provider_error", true) }; }
}
function safeActivity(value: Activity) { const seconds = Math.max(0, Number(value.moving_time ?? 0)); const distance = Math.max(0, Number(value.distance ?? 0)); return { id: String(value.id ?? ""), name: text(value.name).slice(0, 120), type: text(value.sport_type) || text(value.type) || "Activity", startedAt: text(value.start_date), movingMinutes: Math.round(seconds / 60), distanceKm: Number((distance / 1000).toFixed(2)), elevationGainM: Math.max(0, Math.round(Number(value.total_elevation_gain ?? 0))) }; }
function summary(values: Activity[], dates: NonNullable<ReturnType<typeof range>>) { const items = values.map(safeActivity).filter((item) => item.id && item.startedAt); const movingMinutes = items.reduce((total, item) => total + item.movingMinutes, 0); const distanceKm = Number(items.reduce((total, item) => total + item.distanceKm, 0).toFixed(2)); const activeDays = new Set(items.map((item) => item.startedAt.slice(0, 10))).size; const latest = items.map((item) => Date.parse(item.startedAt)).filter(Number.isFinite).sort((a, b) => b - a)[0]; return { provider: "strava", readOnly: true, nonDiagnostic: true, privacy: { preciseRoutesReturned: false, privateOnlyActivitiesRequested: false }, startDate: dates.startDate, endDate: dates.endDate, totals: { activities: items.length, activeDays, movingMinutes, distanceKm }, latestActivityAt: latest ? new Date(latest).toISOString() : null, stale: !latest || Date.now() - latest > 30 * 86_400_000, activities: items, notice: "Activity summaries are general wellness information, not medical advice or an emergency service." }; }
const unsafeGoal = /\b(diagnos|treat|cure|medicat|dosage|prescription|injur(?:y|ies)|rehab|chest pain|suicid|eating disorder|pregnan|emergency|rapid weight|lose \d+\s*(?:kg|lb))\b/i;
function routine(goal: string, startDate: string, data: ReturnType<typeof summary>) { const baseline = data.totals.movingMinutes; const comfortable = baseline > 0 ? Math.max(10, Math.min(30, Math.round(baseline / Math.max(1, data.totals.activeDays)))) : 15; return { provider: "strava", nonDiagnostic: true, goal, startDate, durationDays: 14, sourceWindow: { startDate: data.startDate, endDate: data.endDate, activities: data.totals.activities, stale: data.stale }, schedule: [{ cadence: "3 days each week", action: `Choose a comfortable activity for about ${comfortable} minutes; keep the effort easy enough to speak normally.` }, { cadence: "2 days each week", action: "Use a gentle mobility or rest day based on how you feel." }, { cadence: "weekly", action: "Review comfort and consistency. Keep the same level or reduce it if recovery felt difficult." }], progression: data.stale ? "No progression is suggested because recent source data is unavailable or stale." : "After a comfortable week, add at most five minutes to one session; progression is optional.", safetyNotice: "This is general wellness planning, not diagnosis or treatment. Stop if unwell, seek qualified clinical advice for symptoms, and use emergency services for urgent concerns." }; }
function planHash(goal: string, startDate: string) { return createHash("sha256").update(JSON.stringify({ goal, startDate })).digest("hex"); }
async function persistPlan(input: ProviderExecutionInput, result: ReturnType<typeof routine>) { if (!input.idempotencyKey) return; await prisma.lifeTransaction.create({ data: { userId: input.userId, capabilityKey: "wellness.plan.prepare", executionLevel: "prepare", state: "confirmed", providerId: "strava", providerCandidatesJson: encodeJson(["strava"]), approvalRequired: false, idempotencyKey: input.idempotencyKey, inputJson: encodeJson({ goal: result.goal, startDate: result.startDate, requestHash: planHash(result.goal, result.startDate) }), resultJson: encodeJson(result), completedAt: new Date() } }); }
async function execute(input: ProviderExecutionInput): Promise<ProviderExecutionResult> {
  const toolRunId = input.previousToolRunId ?? randomUUID();
  const preparing = input.capability.key === "wellness.plan.prepare" && input.action === "prepare_action"; const planGoal = text(input.input.goal); const planStartDate = text(input.input.startDate);
  if (preparing) { if (!planGoal || planGoal.length > 200 || !/^\d{4}-\d{2}-\d{2}$/.test(planStartDate)) return blocked(input, "Add a concise wellness goal and start date."); if (unsafeGoal.test(planGoal)) return blocked(input, "This request needs an appropriate healthcare or emergency professional; the wellness planner cannot diagnose, treat, prescribe, or manage urgent concerns."); if (!input.idempotencyKey) return blocked(input, "An idempotency key is required to prepare a wellness plan."); const existing = await prisma.lifeTransaction.findUnique({ where: { userId_idempotencyKey: { userId: input.userId, idempotencyKey: input.idempotencyKey } } }); if (existing) { const storedInput = decodeJson<Record<string, unknown>>(existing.inputJson, {}); if (storedInput.requestHash !== planHash(planGoal, planStartDate)) return blocked(input, "This idempotency key is already bound to another wellness plan."); return { status: "ok", toolRunId, result: decodeJson<Record<string, unknown>>(existing.resultJson, {}) }; } }
  const dates = range(input); if (!dates) return blocked(input, "Choose a valid wellness period of no more than 31 days that does not extend into the future.");
  const found = await activities(input, dates); if ("error" in found) return found.error; const data = summary(found.values, dates);
  if (input.capability.key === "wellness.activity.read" && ["search", "status", "sync_status"].includes(input.action)) return { status: "ok", toolRunId, result: data };
  if (preparing) { const result = routine(planGoal, planStartDate, data); await persistPlan(input, result); return { status: "ok", toolRunId, result }; }
  return blocked(input, "Strava does not support this wellness operation.");
}
export const stravaProvider: ProviderAdapter = { providerId: "strava", label: "Strava", kind: "oauth_api", toolName: "strava.wellness", capabilities: ["wellness.activity.read", "wellness.plan.prepare"], actions: ["search", "status", "sync_status", "prepare_action"], requiresConnectedAccount: true, credentialType: "oauth", credentialFields: [{ key: "accessToken", label: "OAuth access token", type: "password", required: true }, { key: "grantedScopes", label: "Granted OAuth scopes", type: "text", required: false }], oauthConfig: { authUrl: "https://www.strava.com/oauth/authorize", tokenUrl: "https://www.strava.com/api/v3/oauth/token", scopes: ["activity:read"], clientIdEnvKey: "STRAVA_CLIENT_ID", clientSecretEnvKey: "STRAVA_CLIENT_SECRET" }, authType: "oauth", riskLevel: "high", description: "Read-only Strava activity summaries and conservative non-diagnostic wellness planning.", supportsHealthCheck: true, canHandle(input) { if (input.preferredProviderId && input.preferredProviderId !== this.providerId) return false; return input.capabilityKey === "wellness.activity.read" ? ["search", "status", "sync_status"].includes(input.action) : input.capabilityKey === "wellness.plan.prepare" && input.action === "prepare_action"; }, execute, async healthCheck() { return { state: env.LIVE_WELLNESS_ENABLED === "true" ? "healthy" : "disabled", message: env.LIVE_WELLNESS_ENABLED === "true" ? "Strava wellness reads are enabled; connection consent is checked per user." : "Live wellness access is disabled.", checkedAt: new Date().toISOString() }; } };
