import cors from "cors";
import express from "express";
import helmet from "helmet";
import { pinoHttp } from "pino-http";
import { frontendOrigins } from "./config/env.js";
import { logger } from "./config/logger.js";
import { requestContext } from "./middleware/requestContext.js";
import { requestId } from "./middleware/requestId.js";
import { requireUser } from "./middleware/requireUser.js";
import { errorHandler } from "./middleware/errorHandler.js";
import { agentRuntimeRateLimit, generalApiRateLimit, sensitiveActionRateLimit } from "./middleware/rateLimit.js";
import { healthRoutes } from "./routes/healthRoutes.js";
import { agentRoutes } from "./routes/agentRoutes.js";
import { vaultRoutes } from "./routes/vaultRoutes.js";
import { permissionRoutes } from "./routes/permissionRoutes.js";
import { activityRoutes } from "./routes/activityRoutes.js";
import { mcpRoutes } from "./routes/mcpRoutes.js";
import { hitlRoutes } from "./routes/hitlRoutes.js";
import { marketplaceRoutes } from "./routes/marketplaceRoutes.js";
import { creatorRoutes } from "./routes/creatorRoutes.js";
import { creatorAccessRoutes } from "./routes/creatorAccessRoutes.js";
import { moderationRoutes } from "./routes/moderationRoutes.js";
import { installRoutes } from "./routes/installRoutes.js";
import { agentRuntimeRoutes } from "./routes/agentRuntimeRoutes.js";
import { externalAgentImportRoutes } from "./routes/externalAgentImportRoutes.js";
import { toolRoutes } from "./routes/toolRoutes.js";
import { connectorRoutes, publicConnectorRoutes } from "./routes/connectorRoutes.js";
import { workflowConnectionRoutes } from "./routes/workflowConnectionRoutes.js";
import { providerHealthRoutes } from "./routes/providerHealthRoutes.js";
import { providerConnectionRoutes, publicProviderConnectionRoutes } from "./routes/providerConnectionRoutes.js";
import { providerReceiptRoutes } from "./routes/providerReceiptRoutes.js";
import { providerDefinitionRoutes } from "./routes/providerDefinitionRoutes.js";
import { lifePlatformRoutes } from "./routes/lifePlatformRoutes.js";
import { durableJobRoutes } from "./routes/durableJobRoutes.js";
import { travelCheckoutRoutes } from "./routes/travelCheckoutRoutes.js";
import { shoppingCheckoutRoutes } from "./routes/shoppingCheckoutRoutes.js";
import { householdLiveRoutes } from "./routes/householdLiveRoutes.js";
import { betaRoutes } from "./routes/betaRoutes.js";
import { requireBetaAccess } from "./middleware/requireBetaAccess.js";
import { dataRightsRoutes } from "./routes/dataRightsRoutes.js";
import { operationsRoutes } from "./routes/operationsRoutes.js";
import { calComWebhookRoutes } from "./routes/calComWebhookRoutes.js";
import { plaidWebhookRoutes } from "./routes/plaidWebhookRoutes.js";
import { loadActiveProviderDefinitionsIntoRegistry } from "./services/providerDefinitionService.js";

export function createApp() {
  const app = express();
  app.set("trust proxy", 1);
  void loadActiveProviderDefinitionsIntoRegistry().catch((error) => {
    logger.warn({ error }, "could not load persisted provider definitions");
  });
  app.use(helmet());
  app.use(cors({ origin: frontendOrigins, credentials: true }));
  app.use(express.json({ limit: "1mb", verify: (req, _res, buffer) => { (req as express.Request & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } }));
  app.use(requestId);
  app.use(pinoHttp({ logger }));

  app.use("/health", healthRoutes);
  app.use(requestContext);
  app.use("/api", generalApiRateLimit);
  app.use("/api/connectors", publicConnectorRoutes);
  app.use("/api/provider-connections", publicProviderConnectionRoutes);
  app.use("/api/webhooks/cal-com", calComWebhookRoutes);
  app.use("/api/webhooks/plaid", plaidWebhookRoutes);
  app.use("/api", requireUser);
  app.use("/api/beta", betaRoutes);
  app.use("/api", requireBetaAccess);
  app.use("/api/agents", agentRoutes);
  app.use("/api/vault", vaultRoutes);
  app.use("/api/permissions", permissionRoutes);
  app.use("/api/activity", activityRoutes);
  app.use("/api/mcp", mcpRoutes);
  app.use("/api/hitl", hitlRoutes);
  app.use("/api/marketplace", marketplaceRoutes);
  app.use("/api/creator", sensitiveActionRateLimit, creatorRoutes);
  app.use("/api/creator-access", sensitiveActionRateLimit, creatorAccessRoutes);
  app.use("/api/moderation", moderationRoutes);
  app.use("/api/external-agents", sensitiveActionRateLimit, externalAgentImportRoutes);
  app.use("/api/tools", toolRoutes);
  app.use("/api/connectors", connectorRoutes);
  app.use("/api/workflows", workflowConnectionRoutes);
  app.use("/api/provider-connections", providerConnectionRoutes);
  app.use("/api/provider-health", providerHealthRoutes);
  app.use("/api/provider-receipts", providerReceiptRoutes);
  app.use("/api/life-platform", lifePlatformRoutes);
  app.use("/api/privacy/requests", sensitiveActionRateLimit, dataRightsRoutes);
  app.use("/api/travel/hosted-checkout", sensitiveActionRateLimit, travelCheckoutRoutes);
  app.use("/api/shopping/hosted-checkout", sensitiveActionRateLimit, shoppingCheckoutRoutes);
  app.use("/api/household/live", sensitiveActionRateLimit, householdLiveRoutes);
  app.use("/api/admin/providers", sensitiveActionRateLimit, providerDefinitionRoutes);
  app.use("/api/admin/durable-jobs", sensitiveActionRateLimit, durableJobRoutes);
  app.use("/api/admin/operations", sensitiveActionRateLimit, operationsRoutes);
  app.use("/api/me/agents", agentRuntimeRateLimit, agentRuntimeRoutes);
  app.use("/api/me", installRoutes);

  app.use(errorHandler);
  return app;
}
