import type { Dispatch, FormEvent, SetStateAction } from "react";
import type {
  ActivityLog,
  Agent,
  AgentConversation,
  AgentRunResult,
  ExternalAgentImportInput,
  ExternalAgentImportPreview,
  HitlRequest,
  MarketplaceAgent,
  UserAgentInstall,
  VaultDocument,
  VaultSchema
} from "../../api/types";
import type { OnboardingNeed } from "../OnboardingPanel";
import type { RecentInstallSummary } from "../InstallSuccessPanel";
import type { AgentDraft, AgentTemplate } from "../../hooks/useAgentWizard";
import type { AgentProfileTab, ChatTranscriptItem } from "../../hooks/useAgentChat";
import type { HelperStatusFilter } from "../../hooks/useInstalledHelpers";
import type { useCreator } from "../../hooks/useCreator";
import type { useCreatorAccess } from "../../hooks/useCreatorAccess";
import type { useModeration } from "../../hooks/useModeration";
import type { SectionId } from "../../lib/appNavigation";
import type { MatcherChoice, MarketplaceFilters, MarketplaceMatch, MarketplaceNeed } from "../../lib/marketplaceMatching";
import type { HelperPrompt, PermissionReviewItem, ToneState } from "../agent-profile/agentProfileTypes";
export type PermissionProgress = { allowed: number; requested: number; missing: number };
export type VaultItemDraft = { title: string; vaultSchemaId: string; content: string };
export type InstalledAgentCard = {
  agent: Agent;
  readiness: ToneState;
  permissions: PermissionProgress;
  pendingApprovals: number;
};
type AuthSummary = {
  session: { user: { email?: string } } | null;
  signOut: () => void | Promise<void>;
};
export type SetupStep = { label: string; detail: string; done: boolean };

export type WorkspaceSectionsProps = {
  activeMobileClass: (section: SectionId) => string;
  activeSection: SectionId;
  addExternalImport: (input: ExternalAgentImportInput) => Promise<boolean>;
  agentConversation: AgentConversation | null;
  agentDraft: AgentDraft;
  agentProfileTab: AgentProfileTab;
  agentRunResult: AgentRunResult | null;
  agents: Agent[];
  agentTemplates: AgentTemplate[];
  agentWizardStep: number;
  allowedPermissionCount: number;
  applyAgentTemplate: (template: AgentTemplate) => void;
  applyMarketplaceMatcher: () => void;
  approvalPlainSentence: (action: string) => string;
  approvalReason: (action: string) => string;
  approvedContinuation: { requestId: string; actionName: string } | null;
  auth: AuthSummary;
  beginEditVaultItem: (document: VaultDocument) => void;
  canModerateMarketplace: boolean;
  canUseCreatorTools: boolean;
  cancelVaultItemEdit: () => void;
  categoryOptions: string[];
  chatInput: string;
  chatTranscript: ChatTranscriptItem[];
  clearMarketplaceFilters: () => void;
  clearMarketplaceNeedContext: () => void;
  completeGuidedSetup: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  continueApprovedAction: (actionName: string) => void | Promise<void>;
  createAgent: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  createAgentError: string;
  createVaultItem: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  createVaultItemError: string;
  creator: ReturnType<typeof useCreator>;
  creatorAccess: ReturnType<typeof useCreatorAccess>;
  decidingApprovalId: string;
  decideHitl: (requestId: string, approved: boolean) => void | Promise<void>;
  deleteVaultItem: (document: VaultDocument) => void;
  documents: VaultDocument[];
  editingDocumentId: string;
  externalImportError: string;
  externalImportPreview: ExternalAgentImportPreview | null;
  exportMyData: () => void;
  findAnotherAfterInstall: () => void;
  friendlyActionName: (action: string) => string;
  friendlyAppError: (error: unknown) => string;
  friendlyDate: (value: string) => string;
  friendlyFallbackReason: (reason?: string) => string;
  friendlyLogDetail: (log: ActivityLog) => string;
  friendlyLogText: (log: ActivityLog) => string;
  friendlyNotificationText: (log: ActivityLog) => string;
  friendlyTrustLabel: (score: number) => string;
  getStarterInfoPlaceholder: (templateId: string) => string;
  grantAllRequestedSchemas: () => void | Promise<void>;
  grantingSchemaName: string;
  grantRequestedSchema: (schema: VaultSchema) => void | Promise<void>;
  guidedAgentName: string;
  guidedInfoText: string;
  guidedPrompt: string;
  guidedSchema: VaultSchema | undefined;
  guidedSetupError: string;
  guidedSetupStep: number;
  guidedTemplate: AgentTemplate;
  guidedTemplateId: string;
  guidedTemplates: AgentTemplate[];
  hasInstallableMarketplaceAgent: boolean;
  helperNextStep: string;
  helperSearch: string;
  helperStatusFilter: HelperStatusFilter;
  helperStatusFilters: Array<{ id: HelperStatusFilter; label: string }>;
  helperSummary: { ready: number; needsAccess: number; needsApproval: number };
  hiddenTestHelperCount: number;
  hideTestHelpers: boolean;
  hitl: HitlRequest[];
  installedAgents: UserAgentInstall[];
  installedByDefinitionId: Map<string, UserAgentInstall>;
  installedDefinitionIds: Set<string>;
  installingAgentId: string;
  isAddingAgent: boolean;
  isAddingVaultItem: boolean;
  isAgentRunning: boolean;
  isConversationLoading: boolean;
  isCreatingAgent: boolean;
  isCreatingVaultItem: boolean;
  isExternalImportSaving: boolean;
  isGuidedSetupOpen: boolean;
  isGuidedSetupSaving: boolean;
  isHelperAddOpen: boolean;
  isHelperFiltersOpen: boolean;
  isMobileHelperDetailOpen: boolean;
  isRefreshing: boolean;
  isSearchingVault: boolean;
  lastFailedPrompt: string;
  logs: ActivityLog[];
  marketplaceAgents: MarketplaceAgent[];
  marketplaceCategory: string;
  marketplaceCategoryOptions: string[];
  marketplaceError: string;
  marketplaceExamplePrompts: (agent: MarketplaceAgent | undefined) => string[];
  marketplaceFilterLabels: Array<{ id: keyof MarketplaceFilters; label: string }>;
  marketplaceFilters: MarketplaceFilters;
  marketplaceMatchById: Map<string, MarketplaceMatch>;
  marketplaceNeedContext: OnboardingNeed | null;
  marketplaceNeedOptions: MarketplaceNeed[];
  marketplaceSearch: string;
  marketplaceTrustReasons: (agent: MarketplaceAgent | undefined) => string[];
  matcherActions: MatcherChoice;
  matcherNeedId: string;
  matcherPrivateInfo: MatcherChoice;
  mobileInstalledAgentCards: InstalledAgentCard[];
  moderation: ReturnType<typeof useModeration>;
  openAgentWizard: () => void;
  openGuidedSetup: (templateId?: string) => void;
  openMarketplace: () => void;
  openMarketplaceDetails: (agent: MarketplaceAgent) => void;
  openMarketplaceForNeed: (need: OnboardingNeed) => void;
  pendingApproval: HitlRequest | undefined;
  permissionCenterRows: Array<{ schema: VaultSchema; allowedAgents: Agent[]; requestingAgents: Agent[] }>;
  permissionProgress: (agent: Agent | undefined, schemas: VaultSchema[]) => PermissionProgress;
  permissionReview: PermissionReviewItem[];
  pinnedAgentIds: string[];
  primarySetupLabel: string;
  prioritizedMarketplaceAgents: MarketplaceAgent[];
  prioritizedMarketplaceMatches: MarketplaceMatch[];
  promptPreview: ToneState;
  readiness: ToneState;
  recentInstall: RecentInstallSummary | null;
  recentLogs: ActivityLog[];
  refresh: () => Promise<unknown>;
  refreshError: string;
  refreshWithRetry: () => Promise<unknown>;
  reindexVault: () => void | Promise<void>;
  removeAgentFromProfile: (agent: Agent) => void;
  reviewExternalImport: (input: ExternalAgentImportInput) => Promise<ExternalAgentImportPreview | null>;
  reviewRecentInstallAccess: () => void;
  revokeAllAgentAccess: () => void;
  revokeSelectedAgentAccess: () => void;
  runAgentChat: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  runPrimarySetupAction: () => void;
  runSummary: string | null;
  runVaultSearch: () => void | Promise<void>;
  saveVaultEdit: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  schemas: VaultSchema[];
  scrollToSection: (section: SectionId) => void;
  searchQuery: string;
  searchResults: VaultDocument[];
  searchSchemaId: string;
  searchVault: (event: FormEvent<HTMLFormElement>) => void | Promise<void>;
  sectionClass: (section: SectionId) => string;
  selectedAgent: Agent | undefined;
  selectedAgentApprovals: HitlRequest[];
  selectedAgentLogs: ActivityLog[];
  selectedCannotDoLabel: string;
  selectedHelperToolsLabel: string;
  selectedMarketplaceAgent: MarketplaceAgent | undefined;
  selectedReadableInfo: string[];
  selectedReadableInfoLabel: string;
  selectedRiskyActions: string[];
  selectedRiskyActionsLabel: string;
  selectedTemplateId: string;
  setAgentProfileTab: (tab: AgentProfileTab) => void;
  setAgentWizardStep: Dispatch<SetStateAction<number>>;
  setChatInput: (value: string) => void;
  setConfirmInstallAgent: (agent: MarketplaceAgent | null) => void;
  setGuidedInfoText: (value: string) => void;
  setGuidedSetupStep: Dispatch<SetStateAction<number>>;
  setGuidedTemplateId: (templateId: string) => void;
  setHelperSearch: (value: string) => void;
  setHelperStatusFilter: (filter: HelperStatusFilter) => void;
  setHideTestHelpers: (value: boolean) => void;
  setIsAddingAgent: (value: boolean) => void;
  setIsAddingVaultItem: Dispatch<SetStateAction<boolean>>;
  setIsGuidedSetupOpen: (value: boolean) => void;
  setIsHelperAddOpen: Dispatch<SetStateAction<boolean>>;
  setIsHelperFiltersOpen: Dispatch<SetStateAction<boolean>>;
  setMarketplaceCategory: (value: string) => void;
  setMarketplaceError: (value: string) => void;
  setMarketplaceFilters: Dispatch<SetStateAction<MarketplaceFilters>>;
  setMarketplaceSearch: (value: string) => void;
  setMatcherActions: (value: MatcherChoice) => void;
  setMatcherNeedId: (value: string) => void;
  setMatcherPrivateInfo: (value: MatcherChoice) => void;
  setMobileHelperDetailOpen: (value: boolean) => void;
  setRecentInstall: (install: RecentInstallSummary | null) => void;
  setSearchQuery: (value: string) => void;
  setSearchSchemaId: (value: string) => void;
  setSelectedAgentId: (agentId: string) => void;
  setupProgress: number;
  setupSteps: SetupStep[];
  shouldShowOnboarding: boolean;
  showSetupProgress: boolean;
  startupRetryMessage: string;
  submitAgentPrompt: (prompt: string) => void | Promise<void>;
  suggestedPrompts: HelperPrompt[];
  toggleListValue: (values: string[], value: string) => string[];
  togglePermission: (schema: VaultSchema, enabled: boolean) => void | Promise<void>;
  togglePinnedAgent: (agentId: string) => void;
  toolOptions: string[];
  toolResult: string;
  triggerHighRiskAction: () => void | Promise<void>;
  tryRecentInstallPrompt: () => void;
  ungrantedRequestedSchemas: PermissionReviewItem[];
  updateAgentDraft: (patch: Partial<AgentDraft>) => void;
  updateVaultItemDraft: (patch: Partial<VaultItemDraft>) => void;
  uploadVaultFile: (event: FormEvent) => void | Promise<void>;
  vaultItemDraft: VaultItemDraft;
  visibleAgents: Agent[];
  visibleApprovals: HitlRequest[];
  visibleDocuments: VaultDocument[];
  visibleInstalledAgentCards: InstalledAgentCard[];
  visibleMarketplaceAgents: MarketplaceAgent[];
};

